import time
from typing import Any

from openai import OpenAI
from openai import APIConnectionError, APIStatusError, APITimeoutError

from ..config import settings


SYSTEM_PROMPT = """
You are Research Agent, a careful research assistant.

Rules:
- Answer using the provided context when context is available.
- If the context is insufficient, say you do not know from the provided context.
- Be concise, technical, and clear.
"""


def _estimate_tokens(text: str) -> int:
    """
    Rough token estimate for MVP metrics.
    This is not exact. It is only for simple demo metrics.
    """
    if not text:
        return 0
    return max(1, int(len(text.split()) * 1.3))


def _mock_generate(prompt: str, context: str = "") -> dict[str, Any]:
    """
    Deterministic mock LLM.
    This lets the full app run without vLLM/llama.cpp installed.
    """
    if context.strip():
        text = (
            "MOCK ANSWER: Based on the provided context, the uploaded document appears "
            "to discuss the user's question. In the real local-LLM mode, this answer "
            "will be generated by vLLM or llama.cpp using the retrieved document chunks."
        )
    else:
        text = (
            "MOCK ANSWER: No context was provided yet. This confirms the LLM client "
            "abstraction is working. Later phases will connect this to RAG retrieval."
        )

    return {
        "text": text,
        "backend": "mock",
        "model": "mock-llm",
        "mock": True,
        "generation_latency_ms": 0,
        "estimated_tokens_per_second": 0.0,
    }

from collections.abc import Generator


def stream_answer(prompt: str, context: str = "") -> Generator[str, None, None]:
    """
    Streams answer tokens from an OpenAI-compatible LLM backend.

    Works with:
    - llama.cpp server
    - vLLM OpenAI-compatible server
    - other OpenAI-compatible chat servers
    """
    if settings.MOCK_LLM:
        mock_text = _mock_generate(prompt=prompt, context=context)["text"]

        for word in mock_text.split():
            yield word + " "

        return

    client = OpenAI(
        base_url=settings.LLM_BASE_URL,
        api_key=settings.LLM_API_KEY,
    )

    try:
        stream = client.chat.completions.create(
            model=settings.LLM_MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT.strip()},
                {
                    "role": "user",
                    "content": f"Context:\n{context}\n\nUser question:\n{prompt}",
                },
            ],
            temperature=settings.LLM_TEMPERATURE,
            max_tokens=settings.LLM_MAX_TOKENS,
            stream=True,
        )

        for event in stream:
            delta = event.choices[0].delta.content

            if delta:
                yield delta

    except (APIConnectionError, APITimeoutError) as exc:
        yield (
            "\n\n[ERROR] Could not connect to the configured LLM server. "
            "Check LLM_BASE_URL, or set MOCK_LLM=true in .env."
        )

    except APIStatusError as exc:
        yield f"\n\n[ERROR] LLM server returned status={exc.status_code}."

def generate_answer(prompt: str, context: str = "") -> dict[str, Any]:
    """
    Main LLM entrypoint used by the rest of the app.

    MOCK_LLM=true:
        Returns deterministic fake response.

    MOCK_LLM=false:
        Calls an OpenAI-compatible local LLM server,
        such as vLLM or llama.cpp.
    """
    start_time = time.time()

    if settings.MOCK_LLM:
        result = _mock_generate(prompt=prompt, context=context)
        result["generation_latency_ms"] = int((time.time() - start_time) * 1000)
        return result

    client = OpenAI(
        base_url=settings.LLM_BASE_URL,
        api_key=settings.LLM_API_KEY,
    )

    try:
        response = client.chat.completions.create(
            model=settings.LLM_MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT.strip()},
                {
                    "role": "user",
                    "content": f"Context:\n{context}\n\nUser question:\n{prompt}",
                },
            ],
            temperature=settings.LLM_TEMPERATURE,
            max_tokens=settings.LLM_MAX_TOKENS,
        )

        text = response.choices[0].message.content or ""
        elapsed = time.time() - start_time

        estimated_tokens = _estimate_tokens(text)
        tokens_per_second = estimated_tokens / elapsed if elapsed > 0 else 0.0

        return {
            "text": text,
            "backend": settings.LLM_BASE_URL,
            "model": settings.LLM_MODEL,
            "mock": False,
            "generation_latency_ms": int(elapsed * 1000),
            "estimated_tokens_per_second": round(tokens_per_second, 2),
        }

    except (APIConnectionError, APITimeoutError) as exc:
        raise RuntimeError(
            "Could not connect to the configured LLM server. "
            "Check LLM_BASE_URL, or set MOCK_LLM=true in .env."
        ) from exc

    except APIStatusError as exc:
        raise RuntimeError(
            f"LLM server returned an error: status={exc.status_code}, response={exc.response}"
        ) from exc